#!/usr/bin/env ruby

def cmd(cmd, reason, emoji = '✅')
    STDOUT.write "⏱  #{reason}"
    success = system("#{cmd} > /dev/null 2> /dev/null")
    abort "\r🛑\n⚠️  Could not execute: #{cmd}" unless success
    puts "\r#{emoji}"
end
  
branch_name = `git rev-parse --abbrev-ref HEAD`.strip()

puts "Current branch: #{branch_name}"

abort "Cannot do this on master/staging 😉" if branch_name == "master" || branch_name == "staging"

cmd 'git add *', 'Adding files...'
cmd 'git commit --fixup `git log --oneline --decorate --pretty=format:"%H" | head -n 1`', 'Committing...'
cmd "git push --force origin #{branch_name}", 'Pushing...'
